"""add venue osm unique constraint

Revision ID: 28157d5e53bd
Revises: 7706ed95fce6
Create Date: 2026-05-11 22:09:58.432562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28157d5e53bd'
down_revision: Union[str, Sequence[str], None] = '7706ed95fce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_venue_osm', 'venue', ['osm_type', 'osm_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_venue_osm', 'venue', type_='unique')
    # ### end Alembic commands ###
