"""add performer

Revision ID: 34db5ecf3d96
Revises: 7013536cfb36
Create Date: 2026-05-11 21:41:44.187069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34db5ecf3d96'
down_revision: Union[str, Sequence[str], None] = '7013536cfb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ORCHESTRA', 'ENSEMBLE', 'SOLO', 'CHORUS', 'CONDUCTOR', 'OTHER', name='performertype'), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('musicbrainz_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('musicbrainz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performer')
    sa.Enum(name='performertype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
