"""add set list entry and performer

Revision ID: 6a709b7ef3a2
Revises: 28157d5e53bd
Create Date: 2026-05-11 22:16:23.035263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a709b7ef3a2'
down_revision: Union[str, Sequence[str], None] = '28157d5e53bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_list_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('performance_id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('conductor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_list_performer',
    sa.Column('set_list_entry_id', sa.String(), nullable=False),
    sa.Column('performer_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['set_list_entry_id'], ['set_list_entry.id'], ),
    sa.PrimaryKeyConstraint('set_list_entry_id', 'performer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_list_performer')
    op.drop_table('set_list_entry')
    # ### end Alembic commands ###
