"""add performance

Revision ID: 7706ed95fce6
Revises: a06e8e6a293f
Create Date: 2026-05-11 22:03:53.147131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7706ed95fce6'
down_revision: Union[str, Sequence[str], None] = 'a06e8e6a293f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ATTENDED', 'CANCELLED', 'MISSED', 'SKIPPED', name='performancestatus'), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('conductor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['performer.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_performer',
    sa.Column('performance_id', sa.String(), nullable=False),
    sa.Column('performer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performer.id'], ),
    sa.PrimaryKeyConstraint('performance_id', 'performer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_performer')
    op.drop_table('performance')
    # ### end Alembic commands ###
