"""add work

Revision ID: a06e8e6a293f
Revises: 34db5ecf3d96
Create Date: 2026-05-11 21:50:30.301354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06e8e6a293f'
down_revision: Union[str, Sequence[str], None] = '34db5ecf3d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('open_opus_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_opus_id')
    )
    op.create_table('work_composer',
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('composer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'composer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_composer')
    op.drop_table('work')
    # ### end Alembic commands ###
